# .github/workflows/import.yml
name: import

on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: techbrv@my-project-1551724875322.iam.gserviceaccount.com
      - uses: r7kamura/google-docs-to-github@v3
        with:
          google_drive_folder_id: 1byvgNpnn6gA9OSOduKSkX_GXb4LT1F9b
          
          
