# .github/workflows/import.yml
name: import

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account:  ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - uses: r7kamura/google-docs-to-github@v3
        with:
          google_drive_folder_id: 1zD5A9LcT1aHz5_R_eXvikWy1l7SGcjH_
